/* Auto-generated by genmsg_cpp for file /home/ted/ROS/sandbox/sample_action_server/msg/TurnFeedback.msg */
#ifndef SAMPLE_ACTION_SERVER_MESSAGE_TURNFEEDBACK_H
#define SAMPLE_ACTION_SERVER_MESSAGE_TURNFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace sample_action_server
{
template <class ContainerAllocator>
struct TurnFeedback_ {
  typedef TurnFeedback_<ContainerAllocator> Type;

  TurnFeedback_()
  : currentAngle(0)
  {
  }

  TurnFeedback_(const ContainerAllocator& _alloc)
  : currentAngle(0)
  {
  }

  typedef int64_t _currentAngle_type;
  int64_t currentAngle;


  typedef boost::shared_ptr< ::sample_action_server::TurnFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sample_action_server::TurnFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct TurnFeedback
typedef  ::sample_action_server::TurnFeedback_<std::allocator<void> > TurnFeedback;

typedef boost::shared_ptr< ::sample_action_server::TurnFeedback> TurnFeedbackPtr;
typedef boost::shared_ptr< ::sample_action_server::TurnFeedback const> TurnFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sample_action_server::TurnFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sample_action_server::TurnFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sample_action_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sample_action_server::TurnFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sample_action_server::TurnFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sample_action_server::TurnFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e64e05549f9b61851749eb1f6990c745";
  }

  static const char* value(const  ::sample_action_server::TurnFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe64e05549f9b6185ULL;
  static const uint64_t static_value2 = 0x1749eb1f6990c745ULL;
};

template<class ContainerAllocator>
struct DataType< ::sample_action_server::TurnFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sample_action_server/TurnFeedback";
  }

  static const char* value(const  ::sample_action_server::TurnFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sample_action_server::TurnFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int64 currentAngle\n\
\n\
\n\
";
  }

  static const char* value(const  ::sample_action_server::TurnFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::sample_action_server::TurnFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sample_action_server::TurnFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.currentAngle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct TurnFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sample_action_server::TurnFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sample_action_server::TurnFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "currentAngle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.currentAngle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SAMPLE_ACTION_SERVER_MESSAGE_TURNFEEDBACK_H

