/* Auto-generated by genmsg_cpp for file /home/ted/ROS/sandbox/sample_action_server/msg/TurnActionGoal.msg */
#ifndef SAMPLE_ACTION_SERVER_MESSAGE_TURNACTIONGOAL_H
#define SAMPLE_ACTION_SERVER_MESSAGE_TURNACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "sample_action_server/TurnGoal.h"

namespace sample_action_server
{
template <class ContainerAllocator>
struct TurnActionGoal_ {
  typedef TurnActionGoal_<ContainerAllocator> Type;

  TurnActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  TurnActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::sample_action_server::TurnGoal_<ContainerAllocator>  _goal_type;
   ::sample_action_server::TurnGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sample_action_server::TurnActionGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct TurnActionGoal
typedef  ::sample_action_server::TurnActionGoal_<std::allocator<void> > TurnActionGoal;

typedef boost::shared_ptr< ::sample_action_server::TurnActionGoal> TurnActionGoalPtr;
typedef boost::shared_ptr< ::sample_action_server::TurnActionGoal const> TurnActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sample_action_server::TurnActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sample_action_server::TurnActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sample_action_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sample_action_server::TurnActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "566b08a919eec770ee3735c9b72a7892";
  }

  static const char* value(const  ::sample_action_server::TurnActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x566b08a919eec770ULL;
  static const uint64_t static_value2 = 0xee3735c9b72a7892ULL;
};

template<class ContainerAllocator>
struct DataType< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sample_action_server/TurnActionGoal";
  }

  static const char* value(const  ::sample_action_server::TurnActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
TurnGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: sample_action_server/TurnGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
int64 turnId\n\
\n\
";
  }

  static const char* value(const  ::sample_action_server::TurnActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sample_action_server::TurnActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sample_action_server::TurnActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sample_action_server::TurnActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct TurnActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sample_action_server::TurnActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sample_action_server::TurnActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::sample_action_server::TurnGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SAMPLE_ACTION_SERVER_MESSAGE_TURNACTIONGOAL_H

