; Auto-generated. Do not edit!


(cl:in-package sample_action_server-msg)


;//! \htmlinclude TurnGoal.msg.html

(cl:defclass <TurnGoal> (roslisp-msg-protocol:ros-message)
  ((turnId
    :reader turnId
    :initarg :turnId
    :type cl:integer
    :initform 0))
)

(cl:defclass TurnGoal (<TurnGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sample_action_server-msg:<TurnGoal> is deprecated: use sample_action_server-msg:TurnGoal instead.")))

(cl:ensure-generic-function 'turnId-val :lambda-list '(m))
(cl:defmethod turnId-val ((m <TurnGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sample_action_server-msg:turnId-val is deprecated.  Use sample_action_server-msg:turnId instead.")
  (turnId m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnGoal>) ostream)
  "Serializes a message object of type '<TurnGoal>"
  (cl:let* ((signed (cl:slot-value msg 'turnId)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnGoal>) istream)
  "Deserializes a message object of type '<TurnGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'turnId) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnGoal>)))
  "Returns string type for a message object of type '<TurnGoal>"
  "sample_action_server/TurnGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnGoal)))
  "Returns string type for a message object of type 'TurnGoal"
  "sample_action_server/TurnGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnGoal>)))
  "Returns md5sum for a message object of type '<TurnGoal>"
  "5652ef72e93af27756b35a6763446be7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnGoal)))
  "Returns md5sum for a message object of type 'TurnGoal"
  "5652ef72e93af27756b35a6763446be7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnGoal>)))
  "Returns full string definition for message of type '<TurnGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 turnId~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnGoal)))
  "Returns full string definition for message of type 'TurnGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int64 turnId~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnGoal
    (cl:cons ':turnId (turnId msg))
))
