; Auto-generated. Do not edit!


(cl:in-package sample_action_server-msg)


;//! \htmlinclude TurnFeedback.msg.html

(cl:defclass <TurnFeedback> (roslisp-msg-protocol:ros-message)
  ((currentAngle
    :reader currentAngle
    :initarg :currentAngle
    :type cl:integer
    :initform 0))
)

(cl:defclass TurnFeedback (<TurnFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sample_action_server-msg:<TurnFeedback> is deprecated: use sample_action_server-msg:TurnFeedback instead.")))

(cl:ensure-generic-function 'currentAngle-val :lambda-list '(m))
(cl:defmethod currentAngle-val ((m <TurnFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sample_action_server-msg:currentAngle-val is deprecated.  Use sample_action_server-msg:currentAngle instead.")
  (currentAngle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnFeedback>) ostream)
  "Serializes a message object of type '<TurnFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'currentAngle)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnFeedback>) istream)
  "Deserializes a message object of type '<TurnFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'currentAngle) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnFeedback>)))
  "Returns string type for a message object of type '<TurnFeedback>"
  "sample_action_server/TurnFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnFeedback)))
  "Returns string type for a message object of type 'TurnFeedback"
  "sample_action_server/TurnFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnFeedback>)))
  "Returns md5sum for a message object of type '<TurnFeedback>"
  "e64e05549f9b61851749eb1f6990c745")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnFeedback)))
  "Returns md5sum for a message object of type 'TurnFeedback"
  "e64e05549f9b61851749eb1f6990c745")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnFeedback>)))
  "Returns full string definition for message of type '<TurnFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 currentAngle~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnFeedback)))
  "Returns full string definition for message of type 'TurnFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 currentAngle~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnFeedback
    (cl:cons ':currentAngle (currentAngle msg))
))
