; Auto-generated. Do not edit!


(cl:in-package sample_action_server-msg)


;//! \htmlinclude TurnResult.msg.html

(cl:defclass <TurnResult> (roslisp-msg-protocol:ros-message)
  ((angle
    :reader angle
    :initarg :angle
    :type cl:integer
    :initform 0))
)

(cl:defclass TurnResult (<TurnResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurnResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurnResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sample_action_server-msg:<TurnResult> is deprecated: use sample_action_server-msg:TurnResult instead.")))

(cl:ensure-generic-function 'angle-val :lambda-list '(m))
(cl:defmethod angle-val ((m <TurnResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sample_action_server-msg:angle-val is deprecated.  Use sample_action_server-msg:angle instead.")
  (angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurnResult>) ostream)
  "Serializes a message object of type '<TurnResult>"
  (cl:let* ((signed (cl:slot-value msg 'angle)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurnResult>) istream)
  "Deserializes a message object of type '<TurnResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'angle) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurnResult>)))
  "Returns string type for a message object of type '<TurnResult>"
  "sample_action_server/TurnResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurnResult)))
  "Returns string type for a message object of type 'TurnResult"
  "sample_action_server/TurnResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurnResult>)))
  "Returns md5sum for a message object of type '<TurnResult>"
  "4400518c93d5f9762876a1f7ae109f30")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurnResult)))
  "Returns md5sum for a message object of type 'TurnResult"
  "4400518c93d5f9762876a1f7ae109f30")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurnResult>)))
  "Returns full string definition for message of type '<TurnResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurnResult)))
  "Returns full string definition for message of type 'TurnResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurnResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurnResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TurnResult
    (cl:cons ':angle (angle msg))
))
