/* Auto-generated by genmsg_cpp for file /home/ted/ROS/sandbox/ford_msgs/msg/PlannerMode.msg */
#ifndef FORD_MSGS_MESSAGE_PLANNERMODE_H
#define FORD_MSGS_MESSAGE_PLANNERMODE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace ford_msgs
{
template <class ContainerAllocator>
struct PlannerMode_ {
  typedef PlannerMode_<ContainerAllocator> Type;

  PlannerMode_()
  : header()
  , mode(0)
  {
  }

  PlannerMode_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , mode(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _mode_type;
  uint8_t mode;

  enum { DIFF_MP = 0 };
  enum { NN = 1 };
  enum { SPIN_IN_PLACE = 2 };

  typedef boost::shared_ptr< ::ford_msgs::PlannerMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ford_msgs::PlannerMode_<ContainerAllocator>  const> ConstPtr;
}; // struct PlannerMode
typedef  ::ford_msgs::PlannerMode_<std::allocator<void> > PlannerMode;

typedef boost::shared_ptr< ::ford_msgs::PlannerMode> PlannerModePtr;
typedef boost::shared_ptr< ::ford_msgs::PlannerMode const> PlannerModeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ford_msgs::PlannerMode_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ford_msgs::PlannerMode_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ford_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ford_msgs::PlannerMode_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ford_msgs::PlannerMode_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ford_msgs::PlannerMode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42413d5e8ea95803185fd741f1d30a4a";
  }

  static const char* value(const  ::ford_msgs::PlannerMode_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x42413d5e8ea95803ULL;
  static const uint64_t static_value2 = 0x185fd741f1d30a4aULL;
};

template<class ContainerAllocator>
struct DataType< ::ford_msgs::PlannerMode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ford_msgs/PlannerMode";
  }

  static const char* value(const  ::ford_msgs::PlannerMode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ford_msgs::PlannerMode_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint8 mode\n\
uint8 DIFF_MP=0\n\
uint8 NN=1\n\
uint8 SPIN_IN_PLACE=2\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::ford_msgs::PlannerMode_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ford_msgs::PlannerMode_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ford_msgs::PlannerMode_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ford_msgs::PlannerMode_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct PlannerMode_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ford_msgs::PlannerMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ford_msgs::PlannerMode_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FORD_MSGS_MESSAGE_PLANNERMODE_H

